//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainJournal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainJournal()
        {
            this.Customer = new HashSet<CustomersList>();
            this.MVZList = new HashSet<MVZList>();
            this.Type = new HashSet<TypeOfResearch>();
            this.Engineer = new HashSet<ListOfEngineers>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public short NumberOfSamples { get; set; }
        public string Notation { get; set; }
        public StatusEnum Status { get; set; }
        public string StatusDescription { get; set; }
        public string ResearchResults { get; set; }
        public Nullable<TypeOfDefectEnum> TypeOfDefect { get; set; }
        public System.DateTime FinishDate { get; set; }
        public byte[] Document1 { get; set; }
        public byte[] Document2 { get; set; }
        public byte[] Document3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomersList> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVZList> MVZList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfResearch> Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfEngineers> Engineer { get; set; }
        public virtual DataJournal ResearchData { get; set; }
    }
}
