//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MGDBModelContainer : DbContext
    {
        public MGDBModelContainer()
            : base("name=MGDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MainJournal> MainJournalSet { get; set; }
        public virtual DbSet<ListOfEngineers> ListOfEngineersSet { get; set; }
        public virtual DbSet<CustomersList> CustomersListSet { get; set; }
        public virtual DbSet<SamplePrepJournal> SamplePrepJournalSet { get; set; }
        public virtual DbSet<SampleMakingJournal> SampleMakingJournalSet { get; set; }
        public virtual DbSet<MVZList> MVZListSet { get; set; }
        public virtual DbSet<ChemistryJournal> ChemistryJournalSet { get; set; }
        public virtual DbSet<TypeOfResearch> TypeOfResearchSet { get; set; }
        public virtual DbSet<DataJournal> DataJournalSet { get; set; }
    }
}
