//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVZList
    {
        public int Id { get; set; }
        public string MVZ { get; set; }
        public int SampleMakingJournalId { get; set; }
        public int SamplePrepJournalId { get; set; }
        public int ChemistryJournalId { get; set; }
        public int MainJournalId { get; set; }
        public int ChemistryJournalId1 { get; set; }
        public int SamplePrepJournalId1 { get; set; }
        public int SampleMakingJournalId1 { get; set; }
    
        public virtual MainJournal MainJournal { get; set; }
    }
}
